

logging:
  config: classpath:log4j2-dev.xml
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: island
#    password: root
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://47.102.210.203/island?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT

# DataSource Config
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://127.0.0.1:5435/postgres

server:
  port: 8080
